### ISSUE TITLE
Uses JsDoc 3.2 and as such requires Java to be installed

### ISSUE THREAD

**Issue by JohnMurga** [t-ishii/jsdoc-generator#1]
Why not JsDoc 3.3+ which is native Node ?

**Comment by t-ishii** [comment]
Because JsDoc3.3 no supported "Shift-JIS".
You want JsDoc3.3+?

**Comment by JohnMurga** [comment]
Hi, thanks for the reply :-)
I wanted to run the plugin on a machine without Java installed.

**Comment by JohnMurga** [comment]
Awesome ! Thank you :+1:
