### ISSUE TITLE
Output Directory not used?

### ISSUE THREAD

**Issue by netsi1964** [t-ishii/jsdoc-generator#2]
When I change the `Output Directory` in the Settings it does not seem that jsdoc-generator is actually using it. Say I want to output the files to a structure like this:

```
App
  js
docs
  js
    jsdoc
```

The source javascript files would then be in `App/js` folder and the Output Directory setting would then be `../../docs/js/jsdoc`. Running the jsdoc generator package generates a message that it has finished with success, but it does nothing.

**Comment by t-ishii** [comment]
hi.
default current directory is users home directory.

**Comment by netsi1964** [comment]
Default is './out' => a New directory is generates inside js folder: 'app/js/out'
What should I write to make it generate to /docs/js ?

**Comment by t-ishii** [comment]
160ee3fb26
`{pwd}/../../docs/js/jsdoc`

**Comment by julkue** [comment]
@t-ishii The documentation about the paths is really bad.
I've tried everything but I am not able to see any generated documentation as I don't know the path. Why aren't you adding a documentation about using the plugin?

**Comment by t-ishii** [comment]
Sorry.
Just a minute, please. I'll write it by next week.
