### ISSUE TITLE
Please clarify - does this plugin compile existing JsDOC?

### ISSUE THREAD

**Issue by MartinMuzatko** [t-ishii/jsdoc-generator#3]
I was looking for a plugin to generate JsDoc from my typehinted Typescript/Javascript Methods.

Please clarify in the description whether this plugin does compile existing JsDoc to create HTML Documents or creates the JsDoc Annotations

**Comment by t-ishii** [comment]
hi.
sorry. my description was very bad.

rewrote to description. 62b63aa0485e6e07255a8295c930ed8bac2870c5

**Comment by MartinMuzatko** [comment]
Thank you a lot :)
