### ISSUE TITLE
Issue with folders

### ISSUE THREAD

**Issue by leogilardi6** [t-ishii/jsdoc-generator#5]
Hi! I'm using your generator and I'm having some problems with it when the files are in different folders, it's that the right behavior or it have to have a particular way to organize the files into folders to get the tree with the documentation files?
Kind regards!

**Comment by t-ishii** [comment]
Thank you for the issue.
I would like to know a little more about the pattern in which the problem occurs. (Reproduction procedure etc.)

**Comment by leogilardi6** [comment]
Hi! Thanks for reply.
My problem is when I have a hierarchy, for example:
```
MainFolder
-->Folder1
  -->file_3.ts
  -->file_4.ts
-->Folder2
  -->file_5.ts
  -->file_6.ts
-->file_1.ts
-->file_2.ts
```

When I have this kind of structure, I run the script in MainFolder, but the documentation only generates for file_1.ts and file_2.ts only and not for the rest of the files.

**Comment by t-ishii** [comment]
Thank you for the details of detailed trouble.
Although it is the above problem, it was solved by adding the recursive scan option to jsdoc. 👍 

1b2993fc7584964419681431f6f13ed9da6b9489
